### ISSUE TITLE
Firefox  version

### ISSUE THREAD

**Issue by ZNackasha** [RameshAditya/ducky#4]
Is it possible to have a Firefox version of this.

**Comment by Nibot1** [comment]
you can use this firefox extension to install chrom extensions
https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
then go to chrome and navigate to chrome://extension enable the developermode and click on pack extension choose the root folder of the extension an it will generate an .crx file wich you can import with the Firefox extension.  If you dont have Chrome use the .crx file from the attached Zip file wich i've generated about 15min ago for my self.
(i have to put it in a zip file because github don't support .crx file attachements)
[ducky-extension.zip](https://github.com/RameshAditya/ducky/files/2110321/ducky-extension.zip)

!!! Important !!!
you have to use Firefox Developer Edition or Nightly and you have to set "xpinstall.signatures.required" in the about:config to true and restart Firefox.

The only thing is the Duck icon is not shown. Instead you will see an Extension symbol in your Navigationbar

**Comment by RameshAditya** [comment]
@Nibot1 Awesome! I had no idea. I'm referencing this comment into the Readme.md for others to benefit too.

Thanks! 🙂

**Comment by Nibot1** [comment]
No problem.
I read about your project yesterday on devRant

**Comment by Nibot1** [comment]
It is alsow possible to build the extension direct for Firefox with this project https://github.com/mozilla/web-ext
